In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [4]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
 #Preprocess the data
 ## Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1) 
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
#Encoder categorical varibales
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
dataabel_enco

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [9]:
#Onehot encode 'Geography'
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [11]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [13]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
##combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [17]:
##Save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [23]:
##divide the data set into independent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

## Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [24]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [25]:
with open('scaler.pkl','wb')as file:
    pickle.dump(scaler,file)

In [26]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

ANN Implementation

In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# Load sample dataset (e.g., Iris)
iris = load_iris()
X = iris.data       # Features
y = iris.target     # Labels

# Split into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),  # 1st hidden layer
    Dense(32, activation='relu'),  # 2nd hidden layer
    Dense(1, activation='sigmoid')  # Output layer
])

c:\Users\Samjhana Yadav\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [36]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,433 (9.50 KB)

 Trainable params: 2,433 (9.50 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
import tensorflow  
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
tensorflow.keras.losses.BinaryFocalCrossentropy()

In [53]:
# compile the model 
model.compile(optimizer=opt,loss="binary_crossentorpy",metrics=['accuracy'])

In [42]:
# Set up the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [47]:
# Set up Early Stopping 
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [54]:
from keras.losses import BinaryCrossentropy

model.compile(optimizer='adam', loss=BinaryCrossentropy(), metrics=['accuracy'])

In [55]:
# Train the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 6s 304ms/step - accuracy: 0.3158 - loss: 0.1908 - val_accuracy: 0.3000 - val_loss: -0.1374
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.3179 - loss: -0.1601 - val_accuracy: 0.3000 - val_loss: -0.4039
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3273 - loss: -0.2658 - val_accuracy: 0.3000 - val_loss: -0.6207
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3294 - loss: -0.5698 - val_accuracy: 0.3000 - val_loss: -0.8350
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3294 - loss: -0.9745 - val_accuracy: 0.3000 - val_loss: -1.0573
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.3429 - loss: -0.9215 - val_accuracy: 0.3000 - val_loss: -1.2788
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3200 - loss: -1.0958 - val_accuracy: 0.3000 - val_loss: -1.5076
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3398 - loss: -1.3950 - val_accuracy: 0.3000 - val_loss: -1.7562
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3231 - loss: -1.5349 - val_accuracy: 0.3000 - val_loss: -2.0239
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3190 - loss: -1.9416 - val_accuracy: 0.3000 - val_loss: -2.3153
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3398 - loss: -1.8550 - val_accuracy: 0.3000 - val_loss: -2.6297
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.3783 - loss: -2.0463 - val_accuracy: 0.3000 - val_loss: -3.0023
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.3398 - loss: -3.0820 - val_accuracy: 0.3000 - val_loss: -3.4169
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.3627 - loss: -3.1642 - val_accuracy: 0.3000 - val_loss: -3.8526
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.3804 - loss: -3.2233 - val_accuracy: 0.3000 - val_loss: -4.3229
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.3731 - loss: -3.8424 - val_accuracy: 0.3000 - val_loss: -4.8415
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3877 - loss: -4.4764 - val_accuracy: 0.3000 - val_loss: -5.3929
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3575 - loss: -4.6746 - val_accuracy: 0.3000 - val_loss: -5.9745
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.3585 - loss: -4.6132 - val_accuracy: 0.3000 - val_loss: -6.5987
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.3575 - loss: -5.7742 - val_accuracy: 0.3000 - val_loss: -7.2961
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3606 - loss: -6.0787 - val_accuracy: 0.3000 - val_loss: -8.0437
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3544 - loss: -7.7813 - val_accuracy: 0.3000 - val_loss: -8.8659
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.3283 - loss: -9.0572 - val_accuracy: 0.3000 - val_loss: -9.7418
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.3481 - loss: -8.8907 - val_accuracy: 0.3000 - val_loss: -10.6684
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.3210 - loss: -10.5670 - val_accuracy: 0.3000 - val_loss: -11.6816
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3575 - loss: -10.3638 - val_accuracy: 0.3000 - val_loss: -12.7555
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3452 - loss: -10.7371 - val_accuracy: 0.3000 - val_loss: -13.9161
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3340 - loss: -12.0504 - val_accuracy: 0.3000 - val_loss: -15.1818
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3485 - loss: -13.8698 - val_accuracy: 0.3000 - val_loss: -16.5481
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.3756 - loss: -14.5912 - val_accuracy: 0.3000 - val_loss: -18.0134
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.4131 - loss: -14.8883 - val_accuracy: 0.3000 - val_loss: -19.5788
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3527 - loss: -17.9536 - val_accuracy: 0.3000 - val_loss: -21.2694
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3758 - loss: -20.2175 - val_accuracy: 0.3000 - val_loss: -23.0726
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.3354 - loss: -20.8156 - val_accuracy: 0.3000 - val_loss: -24.9351
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3646 - loss: -22.9360 - val_accuracy: 0.3000 - val_loss: -26.9057
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3419 - loss: -25.0253 - val_accuracy: 0.3000 - val_loss: -29.0053
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.3742 - loss: -27.8503 - val_accuracy: 0.3000 - val_loss: -31.2311
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.3825 - loss: -25.4182 - val_accuracy: 0.3000 - val_loss: -33.5563
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3377 - loss: -35.1701 - val_accuracy: 0.3000 - val_loss: -36.0865
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3898 - loss: -33.7758 - val_accuracy: 0.3000 - val_loss: -38.6880
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.3408 - loss: -35.4037 - val_accuracy: 0.3000 - val_loss: -41.4287
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3700 - loss: -33.8673 - val_accuracy: 0.3000 - val_loss: -44.2763
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4096 - loss: -31.4097 - val_accuracy: 0.3000 - val_loss: -47.2351
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3825 - loss: -42.1711 - val_accuracy: 0.3000 - val_loss: -50.4865
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3596 - loss: -47.2255 - val_accuracy: 0.3000 - val_loss: -53.9152
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4013 - loss: -43.2724 - val_accuracy: 0.3000 - val_loss: -57.4267
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3669 - loss: -55.6517 - val_accuracy: 0.3000 - val_loss: -61.2500
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3669 - loss: -55.8897 - val_accuracy: 0.3000 - val_loss: -65.1645
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3554 - loss: -59.0887 - val_accuracy: 0.3000 - val_loss: -69.2402
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.3929 - loss: -59.8609 - val_accuracy: 0.3000 - val_loss: -73.4574
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3481 - loss: -61.9194 - val_accuracy: 0.3000 - val_loss: -77.8910
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.3585 - loss: -60.4066 - val_accuracy: 0.3000 - val_loss: -82.4517
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3669 - loss: -72.7853 - val_accuracy: 0.3000 - val_loss: -87.3137
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3898 - loss: -81.3170 - val_accuracy: 0.3000 - val_loss: -92.4069
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.3721 - loss: -75.4323 - val_accuracy: 0.3000 - val_loss: -97.6163
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3971 - loss: -76.7458 - val_accuracy: 0.3000 - val_loss: -103.0419
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.3919 - loss: -79.3935 - val_accuracy: 0.3000 - val_loss: -108.6583
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3887 - loss: -98.0736 - val_accuracy: 0.3000 - val_loss: -114.5253
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.3554 - loss: -104.1745 - val_accuracy: 0.3000 - val_loss: -120.5241
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.4054 - loss: -104.8929 - val_accuracy: 0.3000 - val_loss: -126.6599
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3200 - loss: -120.3226 - val_accuracy: 0.3000 - val_loss: -133.0247
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3294 - loss: -110.5131 - val_accuracy: 0.3000 - val_loss: -139.4963
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.4200 - loss: -125.3991 - val_accuracy: 0.3000 - val_loss: -146.3411
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.3669 - loss: -134.1389 - val_accuracy: 0.3000 - val_loss: -153.4065
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.3794 - loss: -136.4832 - val_accuracy: 0.3000 - val_loss: -160.6943
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3867 - loss: -116.3049 - val_accuracy: 0.3000 - val_loss: -167.9503
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3533 - loss: -151.1752 - val_accuracy: 0.3000 - val_loss: -175.7809
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3450 - loss: -169.6206 - val_accuracy: 0.3000 - val_loss: -183.9726
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3815 - loss: -162.1381 - val_accuracy: 0.3000 - val_loss: -192.1461
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3648 - loss: -166.7656 - val_accuracy: 0.3000 - val_loss: -200.7021
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.3981 - loss: -191.5258 - val_accuracy: 0.3000 - val_loss: -209.6709
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3752 - loss: -181.5214 - val_accuracy: 0.3000 - val_loss: -218.7227
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3794 - loss: -216.2502 - val_accuracy: 0.3000 - val_loss: -228.2981
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.3690 - loss: -178.6564 - val_accuracy: 0.3000 - val_loss: -237.5747
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3940 - loss: -200.4618 - val_accuracy: 0.3000 - val_loss: -247.3818
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.3596 - loss: -218.0468 - val_accuracy: 0.3000 - val_loss: -257.6133
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3971 - loss: -232.0163 - val_accuracy: 0.3000 - val_loss: -268.1678
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.3721 - loss: -240.2855 - val_accuracy: 0.3000 - val_loss: -278.9342
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.3408 - loss: -256.3615 - val_accuracy: 0.3000 - val_loss: -290.0309
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.3877 - loss: -231.5886 - val_accuracy: 0.3000 - val_loss: -301.1411
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4025 - loss: -232.7431 - val_accuracy: 0.3000 - val_loss: -312.6960
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.3796 - loss: -272.8628 - val_accuracy: 0.3000 - val_loss: -324.7217
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.4085 - loss: -227.1472 - val_accuracy: 0.3000 - val_loss: -336.6324
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3846 - loss: -315.4643 - val_accuracy: 0.3000 - val_loss: -349.4228
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.4346 - loss: -274.6043 - val_accuracy: 0.3000 - val_loss: -361.9918
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4013 - loss: -319.5810 - val_accuracy: 0.3000 - val_loss: -375.2884
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3835 - loss: -338.5309 - val_accuracy: 0.3000 - val_loss: -388.7588
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3783 - loss: -355.9024 - val_accuracy: 0.3000 - val_loss: -402.5591
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.3835 - loss: -392.0142 - val_accuracy: 0.3000 - val_loss: -416.5760
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3827 - loss: -354.6374 - val_accuracy: 0.3000 - val_loss: -430.5395
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.3754 - loss: -375.9692 - val_accuracy: 0.3000 - val_loss: -445.0241
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.4067 - loss: -381.8065 - val_accuracy: 0.3000 - val_loss: -460.0109
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.4002 - loss: -401.5291 - val_accuracy: 0.3000 - val_loss: -475.4611
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.3544 - loss: -441.6423 - val_accuracy: 0.3000 - val_loss: -491.3778
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.3710 - loss: -418.3657 - val_accuracy: 0.3000 - val_loss: -507.4091
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3921 - loss: -437.8931 - val_accuracy: 0.3000 - val_loss: -524.0184
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3608 - loss: -451.1138 - val_accuracy: 0.3000 - val_loss: -540.9736
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3887 - loss: -514.2994 - val_accuracy: 0.3000 - val_loss: -558.5056
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.3648 - loss: -534.3342 - val_accuracy: 0.3000 - val_loss: -576.2822
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.3752 - loss: -480.7367 - val_accuracy: 0.3000 - val_loss: -594.1557

In [56]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [57]:
#load Tensorboard Extension
%load_ext tensorboard

In [60]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 54784), started 0:07:11 ago. (Use '!kill 54784' to kill it.)

In [ ]:
# load the pickle file